### ISSUE TITLE
Multithreading?

### ISSUE THREAD

**Issue by JohanSF** [mmatiaschek/pypdfocr-docker#1]
Took 30 minutes to finish a single file for me. It was a big file but I noticed that only a single cpu thread was in use:
![image](https://user-images.githubusercontent.com/6782603/79440148-f4cc1b00-7fd5-11ea-82eb-df3725cabca0.png)
Any chance for multithreading support?

**Comment by JohanSF** [comment]
Edit: I found out about the config.yaml, trying to specify 16 threads there now and see how long it takes this time.

**Comment by JohanSF** [comment]
Now this is what I like to see :D 
![image](https://user-images.githubusercontent.com/6782603/79441638-c8b19980-7fd7-11ea-8fbf-bc51d0771862.png)
However that was only in the beginning, afterward it only used 1 thread at a time even though I specified 16 threads for both tesseract and preprocessing in the config.
Took 30 minutes again.

**Comment by mmatiaschek** [comment]
thanks for the report, nice to see that somebody is using my wrappers.
However i would suggest to file the issue in the PyPDFOCR repo itself https://github.com/virantha/pypdfocr
I will close your issue as i only provide a dockerfile for an automated build.
all the best!
